CREATE TABLE states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    capital VARCHAR(255),
    population VARCHAR(255),
    language VARCHAR(255),
    area VARCHAR(255),
    established VARCHAR(255),
    about VARCHAR(2000),
    about_capital VARCHAR(2000)
);


INSERT INTO states (name, capital, population, language, area, established, about, about_capital) VALUES
('Andaman & Nicobar', 'Port Blair', '0.4 million', 'Hindi, English', '8,249 km²', '1956', 'A tropical paradise with coral reefs and a colonial history.', 'Port Blair is the capital of Andaman & Nicobar Islands, known for its pristine beaches, marine biodiversity, and historical significance. The city is home to the infamous Cellular Jail and Ross Island.'),
('Andhra Pradesh', 'Amaravati (Proposed), Visakhapatnam (Executive)', '53 million', 'Telugu', '162,968 km²', 'November 1, 1956', 'Andhra Pradesh has a long coastline and is known for its classical dance Kuchipudi.', 'Amaravati is the planned capital city of Andhra Pradesh, located on the banks of the Krishna River. It was designated as the capital after the bifurcation of Andhra Pradesh in 2014, replacing Hyderabad as the capital of the newly formed state. Amaravati is envisioned to be a modern, vibrant city with a blend of ancient culture and advanced infrastructure. The city is planned to include a number of world-class government buildings, residential areas, educational institutions, and recreational facilities. The Andhra Pradesh Capital Region Development Authority (APCRDA) is overseeing its development. With a rich historical significance, Amaravati was once the capital of the Satavahana dynasty and is famous for the Amaravati Stupa, which is a major Buddhist archaeological site.'),
 ('Arunachal Pradesh', 'Itanagar', '1.6 million', 'English', '83,743 km²', 'February 20, 1987', 'Arunachal Pradesh is the northeasternmost state of India, known for its tribal culture and scenic beauty.', 'Itanagar is the capital of Arunachal Pradesh, known for its scenic beauty, Buddhist monasteries, and lush green hills. The city is home to the Ita Fort, Ganga Lake, and the Jawaharlal Nehru Museum.'),
 ('Assam', 'Dispur', '35 million', 'Assamese', '78,438 km²', 'January 26, 1950', 'Assam is known for its tea plantations, rich culture, and the Brahmaputra River.', 'Port Blair is the capital of Andaman & Nicobar Islands, known for its pristine beaches, marine biodiversity, and historical significance. The city is home to the infamous Cellular Jail and Ross Island.'),
('Bihar', 'Patna', '130 million', 'Hindi', '94,163 km²', 'January 26, 1950', 'Bihar has a rich historical and cultural heritage and was home to ancient universities like Nalanda.', 'Patna is the capital of Bihar and one of the oldest continuously inhabited cities in the world. It has a rich historical significance, with landmarks like Golghar, Patna Sahib Gurudwara, and the ruins of Pataliputra.'),
('Chandigarh', 'Chandigarh', '1.1 million', 'Hindi, Punjabi', '114 km²', '1966', 'A planned city serving as capital for both Punjab and Haryana.', 'Chandigarh is the capital of both Punjab and Haryana, known for its modern architecture and urban planning designed by Le Corbusier. It is famous for its clean and green environment, as well as iconic landmarks like the Rock Garden, Sukhna Lake, and Capitol Complex.'),
('Chhattisgarh', 'Raipur', '29 million', 'Hindi', '135,192 km²', 'November 1, 2000', 'Chhattisgarh is known for its forests, waterfalls, and tribal culture.', 'Raipur is the capital of Chhattisgarh, known for its rich tribal culture, historical significance, and growing industrial sector.'),
('Dadra & Nagar Haveli, Daman & Diu', 'Daman', '0.6 million', 'Gujarati, Hindi', '603 km²', 'January 26, 2020', 'A merged UT with Portuguese colonial history and scenic coastlines.', 'Daman is the capital of Dadra and Nagar Haveli and Daman and Diu, known for its scenic coastal beauty, Portuguese colonial heritage, and relaxed atmosphere.'),
  ('Delhi', 'New Delhi', '32 million', 'Hindi', '1,484 km²', '1956', 'India''s capital territory known for historical monuments and political significance.', 'Delhi is the capital of India, known for its historical landmarks, vibrant culture, and diverse cuisine. It is home to iconic sites such as India Gate, Red Fort, Qutub Minar, and Lotus Temple.'),
('Goa', 'Panaji', '1.5 million', 'Konkani', '3,702 km²', 'May 30, 1987', 'Goa is India''s smallest state known for its beaches, tourism, and Portuguese heritage.', 'Panaji is the capital of Goa, known for its scenic beauty, Portuguese heritage, and vibrant nightlife. The city is famous for its colorful streets, historic churches, and beautiful beaches.'),
 ('Gujarat', 'Gandhinagar', '71 million', 'Gujarati', '196,024 km²', 'May 1, 1960', 'Gujarat is known for its business-friendly environment and heritage sites like Somnath.', 'Gandhinagar is the capital of Gujarat, known for its well-planned infrastructure and being home to the famous Akshardham Temple.'),
 ('Haryana', 'Chandigarh', '28 million', 'Hindi', '44,212 km²', 'November 1, 1966', 'Haryana is an agricultural state and a hub for industrial and economic development.', 'Chandigarh is the capital of Haryana, though it also serves as the capital for the neighboring state of Punjab. Known for its modern architecture and design, Chandigarh is a well-planned city with beautiful gardens, lakes, and a rich cultural heritage. The city is known for its clean roads, peaceful environment, and numerous tourist attractions like the Rock Garden and Sukhna Lake. Chandigarh is a hub of administration, business, and education in the region.'),
 ('Himachal Pradesh', 'Shimla (Summer), Dharamshala (Winter)', '7.3 million', 'Hindi', '55,673 km²', 'January 25, 1971', 'Himachal Pradesh is a mountainous state in northern India known for its hill stations and scenic landscapes.', ' Shimla is the capital of Himachal Pradesh and one of the most famous hill stations in India. It is situated in the northwestern Himalayas and known for its colonial architecture, beautiful landscapes, and pleasant weather. Shimla was once the summer capital of British India. It serves as a gateway to the entire state, which is known for its scenic beauty, trekking routes, and temples. Shimla offers a perfect blend of history, nature, and modern tourism.'),
 ('Jammu and Kashmir', 'Srinagar (Summer), Jammu (Winter)', '13.6 million', 'Urdu', '55,538 km²', 'October 31, 2019 (as Union Territory)', 'Known for its breathtaking natural beauty, Jammu and Kashmir is a region in northern India.', 'Srinagar is the summer capital of Jammu & Kashmir, known for its beautiful landscapes, lakes, and rich cultural heritage. Srinagar is famous for the Dal Lake, Mughal gardens, and vibrant handicrafts. The winter capital of the state is Jammu, which has its own unique traditions and significance. Jammu & Kashmir has a long history and is a place of natural beauty and religious importance, home to several significant shrines like Vaishno Devi and Amarnath. '),
('Jharkhand', 'Ranchi', '39 million', 'Hindi', '79,714 km²', 'November 15, 2000', 'Jharkhand is rich in minerals and forest resources and has a large tribal population.', 'Ranchi is the capital of Jharkhand, known for its scenic waterfalls, lush greenery, and tribal culture.'),
 ('Karnataka', 'Bengaluru', '69 million', 'Kannada', '191,791 km²', 'November 1, 1956', 'Karnataka is a hub for technology, home to ancient ruins like Hampi and modern cities like Bengaluru.', 'Bengaluru is the capital of Karnataka, known as the "Silicon Valley of India" due to its thriving IT industry. The city is also famous for its pleasant climate, parks, and historical sites like Bangalore Palace and Lalbagh Botanical Garden.'),
 ('Kerala', 'Thiruvananthapuram', '35 million', 'Malayalam', '38,863 km²', 'November 1, 1956', 'Kerala is famous for its backwaters, literacy rate, and healthcare.', 'Thiruvananthapuram is the capital of Kerala, known for its scenic beauty, backwaters, and rich cultural heritage. The city is home to the famous Padmanabhaswamy Temple and Kovalam Beach.'),
 ('Ladakh', 'Leh', '0.3 million', 'Ladakhi, Urdu', '59,146 km²', 'October 31, 2019 (as Union Territory)', 'Ladakh is a high-altitude desert known for its mountains, monasteries, and unique culture.', 'Leh is the largest city and the summer capital of Ladakh, located in the northernmost part of India. Leh is known for its stunning landscapes, including barren mountains, valleys, and pristine lakes. It serves as the administrative and cultural hub of the region. Leh is also a popular destination for adventure enthusiasts, especially for trekking, mountaineering, and biking tours, and is known for its Tibetan Buddhist culture. Leh is the perfect starting point to explore the mystical land of Ladakh.'),
  ('Lakshadweep', 'Kavaratti', '0.07 million', 'Malayalam, English', '32 km²', '1956', 'An archipelago of coral islands in the Arabian Sea.', 'Kavaratti is the capital of Lakshadweep, known for its beautiful lagoons, coral reefs, and pristine beaches. It is a major tourist attraction and an important administrative hub of the union territory.'),
 ('Madhya Pradesh', 'Bhopal', '84 million', 'Hindi', '308,350 km²', 'November 1, 1956', 'Madhya Pradesh is the "Heart of India", rich in wildlife and historical monuments.', 'Bhopal is the capital of Madhya Pradesh, known for its beautiful lakes, rich heritage, and cultural diversity.'),
('Maharashtra', 'Mumbai', '124 million', 'Marathi', '307,713 km²', 'May 1, 1960', 'Maharashtra is India''s second most populous state and home to Mumbai, the financial capital.', 'Mumbai is the capital of Maharashtra, known as the financial capital of India. It is famous for Bollywood, the Gateway of India, and Marine Drive.'),
('Manipur', 'Imphal', '3 million', 'Meitei (Manipuri)', '22,327 km²', 'January 21, 1972', 'Manipur is known for its classical dance, scenic beauty, and indigenous sports.', 'Imphal is the capital of Manipur, known for its scenic landscapes, rich history, and vibrant culture.'),
('Meghalaya', 'Shillong', '3.3 million', 'English', '22,429 km²', 'January 21, 1972', 'Meghalaya means "abode of clouds" and is known for high rainfall and lush landscapes.', 'Shillong is the capital of Meghalaya, often referred to as the "Scotland of the East" due to its picturesque landscapes, rolling hills, and pleasant climate.'),
 ('Mizoram', 'Aizawl', '1.2 million', 'Mizo', '21,081 km²', 'February 20, 1987', 'Mizoram is a mountainous state with rich biodiversity and vibrant tribal life.', 'Aizawl is the capital of Mizoram, known for its scenic hills, vibrant culture, and traditional Mizo lifestyle.'),
('Nagaland', 'Kohima', '2.2 million', 'English', '16,579 km²', 'December 1, 1963', 'Nagaland is a mountainous state in northeast India with vibrant tribal cultures.', 'Kohima is the capital of Nagaland, known for its rich cultural heritage, scenic landscapes, and historical significance from World War II.'),
 ('Odisha', 'Bhubaneswar', '46 million', 'Odia', '155,707 km²', 'April 1, 1936', 'Odisha is known for the Jagannath Temple, Sun Temple at Konark, and its classical dance forms.', 'Bhubaneswar is the capital of Odisha, known as the "Temple City of India" for its numerous ancient temples and rich cultural heritage.'),
('Puducherry', 'Puducherry', '1.5 million', 'Tamil, Telugu, Malayalam, French', '492 km²', '1954', 'Puducherry is a former French colony known for its beaches, French architecture, and spiritual centers.', 'Puducherry  is the capital of the Union Territory of Puducherry. Known for its colonial French architecture, tree-lined streets, and serene beaches, the city reflects a unique blend of French and Indian culture. The city still retains several French institutions and influences in language, cuisine, and design.'),
 ('Punjab', 'Chandigarh', '30 million', 'Punjabi', '50,362 km²', 'November 1, 1966', 'Punjab is known for its agricultural productivity, vibrant culture, and rich history.', 'Chandigarh is the capital of both Punjab and Haryana, known for its modern architecture and urban planning designed by Le Corbusier. It is famous for its clean and green environment, as well as iconic landmarks like the Rock Garden, Sukhna Lake, and Capitol Complex.'),
('Rajasthan', 'Jaipur', '81 million', 'Hindi', '342,239 km²', 'March 30, 1949', 'Rajasthan is India''s largest state by area, known for its deserts, palaces, and heritage.', 'Jaipur is the capital of Rajasthan and is also known as the "Pink City" due to the distinct color of its buildings. Jaipur is famous for its rich cultural heritage, grand palaces, forts, and vibrant bazaars. As a major tourist destination, it offers historical attractions like the Hawa Mahal, Amber Fort, City Palace, and Jantar Mantar. Jaipur is also a hub for traditional Rajasthani art, handicrafts, and textiles.'),
  ('Sikkim', 'Gangtok', '0.6 million', 'Nepali, English', '7,096 km²', 'May 16, 1975', 'Sikkim is a northeastern state known for its biodiversity, mountains, and monasteries.', 'Gangtok is the capital of Sikkim, known for its breathtaking landscapes, monasteries, and vibrant culture. The city offers stunning views of the Himalayas and serves as a base for exploring destinations like Tsomgo Lake and Nathula Pass.'),
   ('Tamil Nadu', 'Chennai', '78 million', 'Tamil', '130,058 km²', 'January 26, 1950', 'Tamil Nadu is known for its Dravidian architecture, temples, and classical arts.', 'Chennai is the capital of Tamil Nadu, known for its rich cultural heritage, historic temples, and Marina Beach, one of the longest urban beaches in the world.'),
  ('Telangana', 'Hyderabad', '39 million', 'Telugu', '112,077 km²', 'June 2, 2014', 'Telangana is India''s youngest state, known for its technology industry and cultural sites.', 'Hyderabad is the capital of Telangana, known for its rich history, iconic landmarks, and thriving IT industry. The city is famous for the Charminar, Golconda Fort, and the bustling bazaars of Laad Bazaar.'),
 ('Tripura', 'Agartala', '4 million', 'Bengali, Kokborok', '10,491 km²', 'January 21, 1972', 'Tripura is surrounded by Bangladesh and is known for its cultural diversity and temples.', 'Agartala is the capital of Tripura, known for its rich history, royal heritage, and cultural diversity. It is home to the iconic Ujjayanta Palace and vibrant festivals that reflect the state''s traditions.'),
 ('Uttarakhand', 'Dehradun', '11 million', 'Hindi', '53,483 km²', 'November 9, 2000', 'Uttarakhand is famous for its pilgrimage sites and Himalayan landscapes.', 'Dehradun is the capital city of Uttarakhand. Nestled in the foothills of the Himalayas, Dehradun is known for its picturesque landscapes, pleasant climate, and historical significance. It is a major educational hub, with numerous prestigious schools and institutions. The city serves as a gateway to the famous hill stations of Mussoorie, Nainital, and Rishikesh, making it a popular tourist destination. Dehradun is also famous for its proximity to the famous religious shrines of Haridwar and Rishikesh.'),
 ('Uttar Pradesh', 'Lucknow', '241 million', 'Hindi', '243,286 km²', 'January 26, 1950', 'Uttar Pradesh is India''s most populous state and home to the Taj Mahal.', 'Lucknow is the capital of Uttar Pradesh and is renowned for its rich history, culture, and architectural beauty. Known as the "City of Nawabs," Lucknow is famous for its Awadhi cuisine, Mughal-era monuments, and vibrant bazaars. Major attractions include Bara Imambara, Rumi Darwaza, and the British Residency.'),
('West Bengal', 'Kolkata', '100 million', 'Bengali', '88,752 km²', 'January 26, 1950', 'West Bengal is known for its cultural heritage, the Sundarbans, and colonial architecture.', 'Kolkata is the capital of West Bengal, known for its colonial-era architecture, rich literary heritage, and vibrant cultural scene. It is famous for its iconic Howrah Bridge, bustling markets, and delicious Bengali cuisine.'); 


CREATE TABLE foods (
    id BIGINT PRIMARY KEY,
    state_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE CASCADE
);

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(1, 1, 'Seafood Platter', 'A delicious assortment of fresh seafood including lobsters, prawns, and fish, often grilled or spiced with local flavors.', '../Image/AndamanNicobar/SeafoodPlatter.jpg'),
(2, 1, 'Coconut Prawn Curry', 'A flavorful dish made with fresh prawns cooked in coconut milk and aromatic spices, served with rice.', '../Image/AndamanNicobar/CoconutPrawn.jpeg'),
(3, 1, 'Banana Leaf Fish', 'A traditional dish where marinated fish is wrapped in banana leaves and grilled to perfection.', '../Image/AndamanNicobar/BananaLeafFish.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(4, 2, 'Hyderabadi Biryani', 'A flavorful, aromatic rice dish made with basmati rice, meat (usually mutton or chicken), and a blend of spices.', '../Image/AndhraPradesh/Hyderabadi Biryani.jpg'),
(5, 2, 'Pulihora (Tamarind Rice)', 'Pulihora is a tangy, flavorful rice dish made with tamarind, spices, and sometimes peanuts. It’s commonly prepared for festivals and special occasions and is a popular choice for lunch in Andhra Pradesh. The combination of sour tamarind and aromatic spices creates a delightful taste that’s both savory and tangy.', '../Image/AndhraPradesh/Pulihora.jpg'),
(6, 2, 'Pesarattu (Green Gram Pancake)', 'Pesarattu is a savory pancake made from green gram (moong dal), commonly served as a breakfast dish in Andhra Pradesh. It’s typically enjoyed with ginger chutney or coconut chutney, making it a deliciously healthy and filling option. The crispy texture and rich flavor make it a popular choice across the state.', '../Image/AndhraPradesh/Pesarattu.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(7, 3, 'Thukpa', 'A popular noodle soup with vegetables and meat, influenced by Tibetan cuisine, and enjoyed in the cold climate of Arunachal Pradesh.', '../Image/ArunachalPradesh/Thukpa.png'),
(8, 3, 'Momos', 'Steamed dumplings filled with meat or vegetables, served with spicy chutney, a staple food in Arunachal Pradesh.', '../Image/ArunachalPradesh/Momos.png');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(9, 4, 'Assam Laksa', 'A delicious, tangy, and spicy fish-based noodle soup with a unique flavor, widely enjoyed in Assam.', '../Image/Assam/Laksa.jpg'),
(10, 4, 'Masor Tenga', 'A light and tangy fish curry made with tomatoes, lemon, or elephant apple, a staple dish in Assamese cuisine.', '../Image/Assam/Masor Tenga.png');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(11, 5, 'Litti Chokha', 'A signature dish of Bihar, Litti is made from wheat flour dough stuffed with spiced sattu (gram flour) and served with mashed potatoes and roasted eggplant (Chokha).', '../Image/Bihar/Litti Chokha.jpg'),
(12, 5, 'Thekua', 'A deep-fried sweet snack made from wheat flour, jaggery, and ghee, often prepared during Chhath Puja.', '../Image/Bihar/Thekua.jpeg'),
(13, 5, 'Khaja', 'A crispy, layered sweet made from refined flour and sugar syrup, popular in Bihar, especially in Silao.', '../Image/Bihar/Khaja.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(14, 6, 'Chole Bhature', 'A popular North Indian dish consisting of spicy chickpeas served with deep-fried bread, commonly enjoyed as a breakfast or lunch dish.', '../Image/Chandigarh/CholeBhature.jpg'),
(15, 6, 'Paneer Tikka', 'A flavorful dish made from marinated paneer cubes grilled to perfection, often served as a starter.', '../Image/Chandigarh/PaneerTikka.jpeg'),
(16, 6, 'Lassi', 'A refreshing yogurt-based drink, available in sweet and salty flavors, and a favorite beverage in the region.', '../Image/Chandigarh/Lassi.jpeg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(17, 7, 'Chana Samosa', 'A popular snack made by combining samosa with spicy chana (chickpeas), offering a delightful taste.', '../Image/Chhattisgarh/ChanaSamosa.jpg'),
(18, 7, 'Muthia', 'A healthy steamed dumpling made of rice and lentils, enjoyed with chutney.', '../Image/Chhattisgarh/Muthia.jpg'),
(19, 7, 'Faraa', 'A rice dumpling dish, often considered the Chhattisgarhi version of momos.', '../Image/Chhattisgarh/Faraa.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(20, 8, 'Prawns Curry', 'A flavorful seafood dish made with prawns cooked in coconut-based gravy with a blend of spices.', '../Image/DadraNagarHaveliDamanDiu/PrawnsCurry.jpeg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(21, 9, 'Chole Bhature', 'A famous Delhi dish consisting of spicy chickpeas served with deep-fried bread, enjoyed as a breakfast or lunch option.', '../Image/Chandigarh/CholeBhature.jpg'),
(22, 9, 'Paratha', 'A popular North Indian flatbread stuffed with various fillings like potato, paneer, or radish, best enjoyed with butter and pickles.', '../Image/Delhi/Paratha.webp'),
(23, 9, 'Jalebi', 'A sweet treat made by deep-frying flour batter in circular shapes and soaking them in sugar syrup.', '../Image/Delhi/Jalebi.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(24, 10, 'Goan Fish Curry', 'A tangy and spicy coconut-based curry made with fresh fish, a staple dish of Goan cuisine.', '../Image/Goa/GoanFishCurry.webp'),
(25, 10, 'Bebinca', 'A traditional Goan layered dessert made from coconut milk, eggs, and jaggery.', '../Image/Goa/Bebinca.jpg'),
(26, 10, 'Pork Vindaloo', 'A spicy and tangy dish influenced by Portuguese cuisine, made with marinated pork and a flavorful blend of spices.', '../Image/Goa/PorkVindaloo.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(27, 11, 'Dhokla', 'A steamed, spongy snack made from fermented rice and chickpea flour, often enjoyed with chutney.', '../Image/Gujarat/Dhokla.jpg'),
(28, 11, 'Thepla', 'A flatbread made with wheat flour, fenugreek leaves, and spices, perfect for travel and everyday meals.', '../Image/Gujarat/Thepla.jpg'),
(29, 11, 'Fafda Jalebi', 'A popular breakfast combination of crispy gram flour snacks (fafda) paired with sweet jalebi.', '../Image/Gujarat/FafdaJalebi.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(30, 12, 'Chaas', 'Chaas, also known as buttermilk, is a popular drink in Haryana, particularly during the hot summer months. It is made from yogurt and is often flavored with cumin, salt, and black pepper. It is known for its cooling properties and digestive benefits.', '../Image/Haryana/Chaas.jpeg'),
(31, 12, 'Paratha', 'Paratha is a common breakfast or lunch dish in Haryana. It is a flatbread made of whole wheat flour, often stuffed with vegetables like potatoes, cauliflower, or radish. It is served with yogurt, pickle, and a dollop of ghee.', '../Image/Haryana/Paratha.webp'),
(32, 12, 'Bajra Khichdi', 'A hearty dish made from millet (bajra) and moong dal (yellow lentils). This dish is commonly prepared during the winter months and is a staple food in Haryana, especially in rural areas. It is often paired with a dollop of ghee and served with buttermilk.', '../Image/Haryana/Bajra Khichdi.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(33, 13, 'Dham', 'A traditional Himachali feast consisting of rice, dal, and a variety of side dishes, which is usually prepared during special occasions. It is a signature dish of the region and is often served with a mix of flavors like spicy, tangy, and sweet.', '../Image/HimachalPradesh/Dham.webp'),
(34, 13, 'Sidu', 'A steamed bread made from wheat flour, which is usually served with ghee or chutney. Sidu is a popular dish in Himachal Pradesh, especially during festivals and family gatherings.', '../Image/HimachalPradesh/Sidu.jpg'),
(35, 13, 'Chana Madra', 'A delicious curry made from chickpeas and yogurt, flavored with aromatic spices. This dish is a staple in Himachal and is usually eaten with steamed rice.', '../Image/HimachalPradesh/ChanaMadra.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(36, 14, 'Kashmiri Biryani', 'A flavorful rice dish made with aromatic spices, saffron, and meat (usually mutton or chicken). It is rich in flavor and a beloved part of Kashmiri cuisine.', '../Image/JammuKhasmir/Kashmiri Biryani.jpg'),
(37, 14, 'Rogan Josh', 'A traditional Kashmiri dish made with tender lamb cooked in a rich, spicy, and aromatic sauce. It is a key component of the Kashmiri wazwan cuisine and is often enjoyed with steamed rice or naan.', '../Image/JammuKhasmir/Rogan Josh.jpg'),
(38, 14, 'Kahwa', 'A traditional Kashmiri tea made with green tea leaves, saffron, almonds, and a blend of spices. It is a warming drink, especially during cold winters in Kashmir.', '../Image/JammuKhasmir/Kahwa.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(39, 15, 'Litti Chokha', 'A popular dish made of wheat flour stuffed with spiced gram flour, served with mashed potatoes and brinjal.', '../Image/Jharkhand/LittiChokha.webp'),
(40, 15, 'Thekua', 'A deep-fried sweet snack made with wheat flour, jaggery, and ghee, often prepared during festivals.', '../Image/Jharkhand/Thekua.jpg'),
(41, 15, 'Dhuska', 'A traditional fried snack made from rice and lentil batter, commonly eaten with chutney.', '../Image/Jharkhand/Dhuska.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(42, 16, 'Bisi Bele Bath', 'A spicy and flavorful rice dish made with lentils, vegetables, and a special spice mix.', '../Image/Karnataka/BisiBeleBath.jpg'),
(43, 16, 'Mysore Pak', 'A famous Karnataka sweet made from gram flour, sugar, and ghee, originally from the royal kitchens of Mysore.', '../Image/Karnataka/MysorePak.jpg'),
(44, 16, 'Dosa', 'A crispy and thin pancake made from fermented rice and urad dal batter, often served with chutney and sambar.', '../Image/Karnataka/Dosa.jpeg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(45, 17, 'Sadya', 'A traditional vegetarian feast served on a banana leaf, featuring rice, curries, pickles, and payasam.', '../Image/Kerala/Sadya.jpg'),
(46, 17, 'Appam with Stew', 'Soft rice pancakes served with a mildly spiced coconut milk-based stew, usually with vegetables or chicken.', '../Image/Kerala/Appam.webp'),
(47, 17, 'Puttu and Kadala Curry', 'Steamed rice flour cakes paired with a flavorful black chickpea curry, a popular breakfast dish.', '../Image/Kerala/PuttuKadala.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(48, 18, 'Thukpa', 'A traditional noodle soup made with vegetables or meat, and flavored with Tibetan spices. It is a popular dish in Ladakh, especially in the cold winter months.', '../Image/Ladakh/Thukpa.jpg'),
(49, 18, 'Butter Tea (Chai)', 'A unique tea made from yak butter, salt, and tea leaves. This traditional beverage is a vital part of Ladakhi culture, providing warmth and energy to help cope with the extreme cold.', '../Image/Ladakh/Butter Tea.jpg'),
(50, 18, 'Momos', 'Steamed or fried dumplings filled with vegetables or meat. These savory treats are very popular in Ladakh and are often enjoyed as a snack or appetizer.', '../Image/Ladakh/Momo.cms');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(51, 19, 'Tuna Curry', 'A popular dish in Lakshadweep made with fresh tuna fish, coconut, and traditional spices.', '../Image/Lakshadweep/TunaCurry.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(52, 20, 'Poha Jalebi', 'A popular breakfast dish in Madhya Pradesh, consisting of flattened rice (poha) served with crispy and sweet jalebi.', '../Image/MadhyaPradesh/PohaJaleb.webp'),
(53, 20, 'Bhutte Ka Kees', 'A unique dish made from grated corn cooked with spices and milk, offering a deliciously rich flavor.', '../Image/MadhyaPradesh/BhutteKaKees.avif'),
(54, 20, 'Dal Bafla', 'A traditional dish similar to Rajasthani Dal Baati, made of wheat balls served with spicy dal and ghee.', '../Image/MadhyaPradesh/DalBafla.jpeg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(55, 21, 'Vada Pav', 'A popular street food consisting of a spicy potato fritter inside a bun, served with chutneys.', '../Image/Maharashtra/VadaPav.webp'),
(56, 21, 'Puran Poli', 'A sweet flatbread stuffed with jaggery and lentils, commonly prepared during festivals.', '../Image/Maharashtra/PuranPoli.jpg'),
(57, 21, 'Misal Pav', 'A spicy curry made of sprouted lentils, topped with crunchy farsan, served with bread.', '../Image/Maharashtra/MisalPav.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(58, 22, 'Eromba', 'A traditional dish made with mashed boiled vegetables and fermented fish, flavored with aromatic herbs.', '../Image/Manipur/Eromba.jpg'),
(59, 22, 'Singju', 'A popular salad made with raw vegetables, herbs, and a mix of spicy seasonings.', '../Image/Manipur/Singju.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(60, 23, 'Jadoh', 'A popular Khasi dish made with red rice and pork, cooked with aromatic spices for a rich and flavorful experience.', '../Image/Meghalaya/Jadoh.webp'),
(61, 23, 'Doh Khlieh', 'A refreshing and healthy pork salad made with onions, chilies, and spices, often served with rice.', '../Image/Meghalaya/Doh Khlieh.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(62, 24, 'Bai', 'A traditional Mizo dish made with boiled vegetables, bamboo shoots, and pork, often flavored with local herbs.', '../Image/Mizoram/Bai.png'),
(63, 24, 'Vawksa Rep', 'A popular smoked pork dish, cooked with aromatic spices and herbs.', '../Image/Mizoram/VawksaRep.jpg'),
(64, 24, 'Misa Mach Poora', 'A delicious grilled shrimp dish prepared with local spices.', '../Image/Mizoram/MisaMachPoora.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(65, 25, 'Smoked Pork', 'A signature Naga dish made by smoking pork with bamboo shoot and local spices, giving it a unique and delicious flavor.', '../Image/Nagaland/Smoked Pork.jpg'),
(66, 25, 'Axone', 'A fermented soybean dish, commonly used in various Naga cuisines, known for its strong aroma and rich taste.', '../Image/Nagaland/Axone.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(67, 26, 'Dalma', 'A traditional dish made of lentils cooked with vegetables and mild spices, served with rice.', '../Image/Odisha/Dalma.jpg'),
(68, 26, 'Chhena Poda', 'A famous dessert made from baked ricotta cheese, sugar, and cardamom.', '../Image/Odisha/ChhenaPoda.jpg'),
(69, 26, 'Pakhala', 'Fermented rice soaked in water, often enjoyed during hot summers for its cooling effect.', '../Image/Odisha/Pakhala.webp');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(70, 27, 'French Baguette', 'A staple influenced by the French colonial era, the baguette is a popular bread item in Puducherry bakeries.', '../Image/Puducherry/FrenchBaguette.jpg'),
(71, 27, 'Puducherry Fish Curry', 'A spicy and tangy seafood dish cooked with local spices and tamarind, showcasing Tamil coastal flavors with a French twist.', '../Image/Puducherry/FishCurry.png'),
(72, 27, 'Crepes', 'French-style thin pancakes served with sweet or savory fillings, popular in local cafes and eateries.', '../Image/Puducherry/Crepes.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(73, 28, 'Butter Chicken', 'Butter chicken, also known as Murgh Makhani, is a famous Punjabi dish consisting of chicken cooked in a rich and creamy tomato-based gravy. It is often paired with naan or rice and is a favorite among food lovers across the world.', '../Image/Punjab/ButterChicken.jpg'),
(74, 28, 'Chole Bhature', 'A traditional Punjabi dish, Chole Bhature consists of spicy chickpeas (chole) served with fried bread (bhature). It is a popular breakfast and lunch dish, often accompanied by pickles and yogurt.', '../Image/Chandigarh/CholeBhature.jpg'),
(75, 28, 'Amritsari Kulcha', 'Amritsari Kulcha is a popular stuffed flatbread from the city of Amritsar. The bread is filled with spiced mashed potatoes and baked in a tandoor, giving it a crispy exterior and soft interior. It is served with curd, pickles, and chole (spicy chickpeas).', '../Image/Punjab/Amritsari Kulche.avif');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(76, 29, 'Dal Baati Churma', 'This iconic Rajasthani dish consists of dal (lentils), baati (wheat bread), and churma (a sweet, crushed wheat dish). It is a wholesome, flavorful meal enjoyed across Rajasthan, often served with ghee, pickles, and yogurt.', '../Image/Rajasthan/Dal Baati Churma.webp'),
(77, 29, 'Gatte ki Sabzi', 'A savory curry made with gram flour (besan) dumplings, this dish is a specialty of Rajasthan. The gattas are cooked in a spicy gravy, and it is typically served with roti or rice.', '../Image/Rajasthan/Gatte ki Sabzi.jpg'),
(78, 29, 'Malai Ghevar', 'A traditional Rajasthani dessert made during festivals like Teej and Raksha Bandhan, Ghevar is a round-shaped sweet made from flour, ghee, and sugar syrup, topped with fresh cream (malai).', '../Image/Rajasthan/Malai Ghevar.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(79, 30, 'Momos', 'A popular Tibetan-influenced dish, momos are steamed dumplings filled with vegetables or meat, served with spicy chutney.', '../Image/Sikkim/Momos.png'),
(80, 30, 'Thukpa', 'A hearty noodle soup with vegetables and meat, influenced by Tibetan cuisine and enjoyed in the cold weather of Sikkim.', '../Image/Sikkim/Thukpa.png');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(81, 31, 'Idli', 'A popular South Indian breakfast dish made from fermented rice and urad dal batter, served with chutney and sambar.', '../Image/TamilNadu/Idli.jpg'),
(82, 31, 'Chettinad Chicken', 'A spicy and aromatic chicken dish from the Chettinad region, known for its use of freshly ground spices.', '../Image/TamilNadu/ChettinadChicken.jpg'),
(83, 31, 'Pongal', 'A traditional Tamil dish made with rice, lentils, and ghee, commonly eaten during the Pongal festival.', '../Image/TamilNadu/Pongal.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(84, 32, 'Hyderabadi Biryani', 'A world-famous aromatic biryani made with basmati rice, saffron, and marinated meat, cooked using the traditional dum method.', '../Image/Telangana/HyderabadiBiryani.webp'),
(85, 32, 'Sarva Pindi', 'A savory rice flour pancake mixed with peanuts, sesame seeds, and spices, traditionally cooked on a griddle.', '../Image/Telangana/SarvaPindi.avif'),
(86, 32, 'Double Ka Meetha', 'A popular Hyderabadi dessert made from fried bread slices soaked in milk, sugar, and garnished with dry fruits.', '../Image/Telangana/DoubleKaMeetha.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(87, 33, 'Mui Borok', 'A traditional Tripuri dish made with dried and fermented fish, known for its unique flavor.', '../Image/Tripura/MuiBorok.jpg'),
(88, 33, 'Bamboo Shoot Curry', 'A popular dish in Tripura, made with bamboo shoots, herbs, and spices.', '../Image/Tripura/BambooShootCurry.jpeg'),
(89, 33, 'Wahan Mosdeng', 'A delicious pork dish prepared with chilies, onion, and coriander.', '../Image/Tripura/WahanMosdeng.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(90, 34, 'Aloo Ke Gutke', 'A popular dish in Uttarakhand, Aloo Ke Gutke consists of potatoes cooked with various spices. It is often served as a side dish along with rice or roti. The dish has a distinct flavor due to the use of local spices and herbs.', '../Image/Uttarakhand/Aloo Ke Gutke.jpg'),
(91, 34, 'Kafuli', 'Kafuli is a traditional vegetarian curry made with spinach or fenugreek leaves and cooked with yogurt and various spices. It is a healthy and flavorful dish, often served with rice or roti in Uttarakhand.', '../Image/Uttarakhand/Kafuli.jpg'),
(92, 34, 'Chainsoo', 'Chainsoo is a popular dish made from roasted black gram lentils (urad dal). The lentils are ground and cooked with a blend of spices, creating a rich and flavorful dish. It is typically served with rice and is a staple in Uttarakhand''s cuisine.', '../Image/Uttarakhand/Chainsoo.png');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(93, 35, 'Tunday Kababi', 'A world-famous kebab originating from Lucknow, known for its soft texture and flavorful spices. It is made from finely minced meat blended with a secret mix of spices.', '../Image/UttarPradesh/Tunday Kababi.avif'),
(94, 35, 'Peda', 'A sweet delicacy from Mathura made from condensed milk and sugar, often offered as prasad in temples.', '../Image/UttarPradesh/Peda.png'),
(95, 35, 'Baati Chokha', 'A traditional dish from eastern Uttar Pradesh, consisting of baked wheat balls (baati) served with mashed spiced potatoes and lentils.', '../Image/UttarPradesh/BaatiChokha.jpg');

INSERT INTO foods (id, state_id, name, description, image_url) VALUES
(96, 36, 'Rosogolla', 'A famous Bengali sweet made of chhena (cottage cheese) and sugar syrup.', '../Image/WestBengal/Rosogolla.jpg'),
(97, 36, 'Macher Jhol', 'A traditional Bengali fish curry cooked with potatoes, tomatoes, and spices.', '../Image/WestBengal/MacherJhol.jpg'),
(98, 36, 'Shukto', 'A unique Bengali dish made with a mix of vegetables, bitter gourd, and a mild mustard-based gravy.', '../Image/WestBengal/Shukto.jpg');



CREATE TABLE tourist_places (
    id BIGINT PRIMARY KEY,
    state_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE CASCADE
);

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(1, 1, 'Radhanagar Beach', 'One of Asia’s most beautiful beaches, located on Havelock Island, known for its crystal-clear waters and white sandy shores.', '../Image/AndamanNicobar/RadhanagarBeach.jpeg'),
(2, 1, 'Cellular Jail', 'A historical site that played a crucial role in India''s freedom struggle, now serving as a museum and light & sound show venue.', '../Image/AndamanNicobar/CellularJail.jpg'),
(3, 1, 'Neil Island', 'A serene destination known for its coral reefs, lush greenery, and picturesque beaches like Laxmanpur and Bharatpur.', '../Image/AndamanNicobar/NeilIsland.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(4, 2, 'Tirupati Temple', 'Tirupati is one of the most famous pilgrimage destinations in India, known for the Sri Venkateswara Temple. Devotees from all over the world visit to seek the blessings of Lord Venkateswara. The temple is situated atop the Tirumala hills, offering breathtaking views and a serene atmosphere.', '../Image/AndhraPradesh/Tirupati temple.avif'),
(5, 2, 'Araku Valley', 'Araku Valley is a scenic hill station located in the Eastern Ghats, known for its lush greenery, coffee plantations, and pleasant climate. The valley offers a perfect escape from the heat, with its picturesque landscapes and vibrant tribal culture. It is a popular destination for trekking and nature walks.', '../Image/AndhraPradesh/Araku valley.jpg'),
(6, 2, 'Visakhapatnam Beaches', 'Visakhapatnam, also known as Vizag, is home to some of the most beautiful beaches in Andhra Pradesh. The beaches, such as Rushikonda and Yarada, offer stunning views of the coastline and are ideal for relaxation, beach sports, and water activities. Vizag is also known for its rich cultural heritage and the scenic beauty of the surrounding hills and coastline.', '../Image/AndhraPradesh/Visakhapatnam Beach.webp');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(7, 3, 'Tawang Monastery', 'The largest monastery in India, offering spiritual serenity and stunning views of the Tawang Valley.', '../Image/ArunachalPradesh/Tawang Monastery.png'),
(8, 3, 'Sela Pass', 'A high-altitude mountain pass offering breathtaking views and serving as a gateway to Tawang.', '../Image/ArunachalPradesh/Sela Pass.png');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(9, 4, 'Kaziranga National Park', 'A UNESCO World Heritage Site, famous for its one-horned rhinoceroses and diverse wildlife.', '../Image/Assam/Kaziranga National Park.png'),
(10, 4, 'Kamakhya Temple', 'A revered Shakti Peetha temple in Guwahati, known for its spiritual significance and grand Ambubachi Mela festival.', '../Image/Assam/Kamakhya Temple.png');
INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(11, 5, 'Mahabodhi Temple', 'A UNESCO World Heritage Site in Bodh Gaya, where Lord Buddha attained enlightenment under the Bodhi tree.', '../Image/Bihar/Mahabodhi Temple.png'),
(12, 5, 'Nalanda University', 'The ancient center of learning, renowned for its historical significance and contribution to Buddhist studies.', '../Image/Bihar/Nalanda University.png'),
(13, 5, 'Vikramshila University', 'An ancient Buddhist learning center, known for its contributions to Tantric Buddhism and scholarly excellence.', '../Image/Bihar/VikramshilaUniversity.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(14, 6, 'Rock Garden', 'A unique sculpture garden created from industrial and home waste, featuring fascinating art pieces.', '../Image/Chandigarh/RockGarden.jpg'),
(15, 6, 'Sukhna Lake', 'A picturesque man-made reservoir offering boating, jogging tracks, and a tranquil environment for visitors.', '../Image/Chandigarh/SukhnaLake.jpg'),
(16, 6, 'Rose Garden', 'The largest rose garden in Asia, home to thousands of rose varieties and a beautiful place for nature lovers.', '../Image/Chandigarh/RoseGarden.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(17, 7, 'Chitrakote Falls', 'Known as the "Niagara Falls of India," this waterfall in Bastar is a breathtaking sight.', '../Image/Chhattisgarh/ChitrakoteFalls.jpg'),
(18, 7, 'Bhoramdeo Temple', 'An ancient temple dedicated to Lord Shiva, often compared to the Khajuraho temples.', '../Image/Chhattisgarh/BhoramdeoTemple.jpg'),
(19, 7, 'Kanger Valley National Park', 'A biodiversity hotspot with caves, waterfalls, and diverse flora and fauna.', '../Image/Chhattisgarh/KangerValleyNationalPark.jpeg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(20, 8, 'Jampore Beach', 'A serene and clean beach in Daman, ideal for relaxation, adventure activities, and enjoying the sunset.', '../Image/DadraNagarHaveliDamanDiu/JamporeBeach.jpeg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(21, 9, 'India Gate', 'A war memorial dedicated to soldiers of the Indian Army, surrounded by lush green lawns and a popular tourist attraction.', '../Image/Delhi/IndiaGate.jpg'),
(22, 9, 'Qutub Minar', 'A UNESCO World Heritage Site, this tall minaret is a symbol of Delhi rich history and architectural excellence.', '../Image/Delhi/QutubMinar.jpg'),
(23, 9, 'Lotus Temple', 'A stunning architectural marvel shaped like a lotus flower, open to people of all religions for meditation and prayer.', '../Image/Delhi/LotusTemple.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(24, 10, 'Baga Beach', 'One of the most famous beaches in Goa, known for its lively shacks, water sports, and nightlife.', '../Image/Goa/BagaBeach.jpg'),
(25, 10, 'Dudhsagar Falls', 'A majestic four-tiered waterfall located on the Goa-Karnataka border, surrounded by lush greenery.', '../Image/Goa/DudhsagarFalls.jpg'),
(26, 10, 'Basilica of Bom Jesus', 'A UNESCO World Heritage Site that houses the remains of St. Francis Xavier, showcasing exquisite Baroque architecture.', '../Image/Goa/BasilicaBomJesus.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(27, 11, 'Statue of Unity', 'Tallest statue, dedicated to Sardar Vallabhbhai Patel, located near the Narmada River.', '../Image/Gujarat/StatueofUnity.avif'),
(28, 11, 'Gir National Park', 'The only place in the world where Asiatic lions roam freely in their natural habitat.', '../Image/Gujarat/GirNationalPark.jpeg'),
(29, 11, 'Rann of Kutch', 'A vast white salt desert that hosts the famous Rann Utsav, showcasing Gujarats vibrant culture.', '../Image/Gujarat/RannOfKutch.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(30, 12, 'Sultanpur Bird Sanctuary', 'Located near Gurgaon, Sultanpur Bird Sanctuary is a famous bird-watching destination in Haryana. The sanctuary is home to hundreds of species of migratory and resident birds, making it a popular spot for nature lovers and photographers.', '../Image/Haryana/Sultanpur Bird Sanctuary.jpg'),
(31, 12, 'Pinjore Gardens', 'Pinjore Gardens is a historical garden in the town of Pinjore. It was designed by the Mughal emperors and is known for its lush green landscapes, fountains, and scenic beauty. It is a popular tourist spot and is often visited by locals for picnics and leisure walks.', '../Image/Haryana/Pinjore Gardens.webp'),
(32, 12, 'Baba Farid Tomb', 'Baba Farid Tomb, located in Faridabad, is an important historical and spiritual site in Haryana. The tomb is dedicated to the famous Sufi saint Baba Farid and is visited by pilgrims and tourists alike for its tranquility and historical significance.', '../Image/Haryana/Baba Farid Tomb.webp');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(33, 13, 'Manali', 'Manali is a beautiful hill station located in the Kullu Valley. It is known for its adventure sports, scenic landscapes, and vibrant atmosphere. Popular activities in Manali include trekking, skiing, paragliding, and rafting. The town is also known for its temples, including the Hadimba Temple.', '../Image/HimachalPradesh/Manali.webp'),
(34, 13, 'Spiti Valley', 'Known as "Little Tibet," Spiti Valley is a remote desert mountain valley located in the north-eastern part of Himachal Pradesh. The valley is famous for its Buddhist monasteries, stunning landscapes, and trekking trails. The valley is also home to ancient villages, including Kibber and Tabo, and offers an offbeat destination for adventure and cultural exploration.', '../Image/HimachalPradesh/Spiti Valley.jpeg'),
(35, 13, 'Kullu', 'Known as the "Valley of Gods," Kullu is famous for its scenic beauty, apple orchards, and temples. It is a great destination for nature lovers and adventure seekers, with activities such as rafting, trekking, and camping.', '../Image/HimachalPradesh/Kullu.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(36, 14, 'Dal Lake', 'Located in Srinagar, Dal Lake is one of the most famous tourist destinations in Jammu & Kashmir, known for its beautiful houseboats, shikaras, and picturesque surroundings. It is often referred to as the "Jewel in the crown of Kashmir".', '../Image/JammuKhasmir/Dal Lake.jpg'),
(37, 14, 'Gulmarg', 'A popular hill station and skiing destination, Gulmarg is known for its lush green meadows, snow-covered peaks, and the famous Gulmarg Gondola, one of the highest cable cars in the world.', '../Image/JammuKhasmir/Gulmarg.avif'),
(38, 14, 'Amarnath Cave', 'Located at an altitude of 3,888 meters, this sacred cave is a significant pilgrimage site for Hindus. The Amarnath Yatra is held annually and attracts thousands of devotees seeking blessings from the ice Shiva Lingam.', '../Image/JammuKhasmir/Amarnath Cave.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(39, 15, 'Betla National Park', 'A wildlife sanctuary known for its diverse flora and fauna, including elephants and tigers.', '../Image/Jharkhand/BetlaNationalPark.jpg'),
(40, 15, 'Hundru Falls', 'A stunning waterfall located near Ranchi, offering breathtaking views and picnic spots.', '../Image/Jharkhand/HundruFalls.jpg'),
(41, 15, 'Baidyanath Temple', 'A famous Jyotirlinga shrine located in Deoghar, attracting thousands of devotees.', '../Image/Jharkhand/BaidyanathTemple.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(42, 16, 'Hampi', 'A UNESCO World Heritage Site, known for its stunning Vijayanagara Empire ruins and ancient temples.', '../Image/Karnataka/Hampi.webp'),
(43, 16, 'Coorg', 'A scenic hill station famous for its coffee plantations, lush greenery, and waterfalls.', '../Image/Karnataka/Coorg.webp'),
(44, 16, 'Mysore Palace', 'A grand and opulent palace showcasing Indo-Saracenic architecture, illuminated beautifully during festivals.', '../Image/Karnataka/MysorePalace.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(45, 17, 'Alleppey Backwaters', 'Known as the "Venice of the East," Alleppey is famous for its houseboat cruises and scenic backwaters.', '../Image/Kerala/AlleppeyBackwaters.png'),
(46, 17, 'Munnar', 'A picturesque hill station known for its tea plantations, cool climate, and beautiful landscapes.', '../Image/Kerala/Munnar.jpeg'),
(47, 17, 'Kochi', 'A historic port city known for its Chinese fishing nets, Fort Kochi, and colonial architecture.', '../Image/Kerala/Kochi.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(48, 18, 'Pangong Lake', 'Pangong Lake is a stunning high-altitude lake, known for its crystal-clear waters and breathtaking beauty. The lake, located at an altitude of 4,350 meters, is famous for changing colors throughout the day and has been featured in several Bollywood films.', '../Image/Ladakh/Pangong Lake.jpg'),
(49, 18, 'Leh Palace', 'Built in the 17th century, the Leh Palace offers stunning views of the Leh town and the surrounding Himalayan ranges. This ancient structure is a fine example of Tibetan architecture and once served as the residence of the kings of Ladakh.', '../Image/Ladakh/Leh Palace.jpg'),
(50, 18, 'Magnetic Hill', 'Magnetic Hill is a famous phenomenon where vehicles appear to move uphill on their own due to an optical illusion. This unique place attracts curious visitors and is a popular stop for tourists traveling to Ladakh.', '../Image/Ladakh/Magnetic Hill.png');
INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(51, 19, 'Agatti Island', 'A picturesque island known for its stunning coral reefs, clear waters, and adventure activities like snorkeling and scuba diving.', '../Image/Lakshadweep/AgattiIsland.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(52, 20, 'Khajuraho Temples', 'A UNESCO World Heritage Site known for its intricate and erotic sculptures, showcasing India architectural excellence.', '../Image/MadhyaPradesh/KhajurahoTemples.jpg'),
(53, 20, 'Bhimbetka Caves', 'Prehistoric rock shelters with ancient cave paintings, offering a glimpse into early human civilization.', '../Image/MadhyaPradesh/BhimbetkaCaves.jpg'),
(54, 20, 'Kanha National Park', 'One of India premier tiger reserves, known for its rich biodiversity and scenic landscapes.', '../Image/MadhyaPradesh/KanhaNationalPark.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(55, 21, 'Gateway of India', 'A historic arch monument in Mumbai, built to commemorate the landing of King George V and Queen Mary in 1911.', '../Image/Maharashtra/GatewayOfIndia.jpg'),
(56, 21, 'Ajanta & Ellora Caves', 'UNESCO World Heritage Sites showcasing stunning rock-cut Buddhist, Hindu, and Jain temples.', '../Image/Maharashtra/AjantaElloraCaves.webp'),
(57, 21, 'Matheran', 'A serene hill station known for its breathtaking viewpoints and eco-friendly policies.', '../Image/Maharashtra/Matheran.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(58, 22, 'Loktak Lake', 'The largest freshwater lake in Northeast India, famous for its floating islands called phumdis.', '../Image/Manipur/LoktakLake.cms'),
(59, 22, 'Kangla Fort', 'A historical and cultural landmark in Imphal, showcasing Manipur royal heritage.', '../Image/Manipur/KanglaFort.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(60, 23, 'Living Root Bridges', 'These unique bridges, made from intertwined roots of rubber trees, are a marvel of bioengineering and found in the dense forests of Meghalaya.', '../Image/Meghalaya/Living Root Bridges.jpg'),
(61, 23, 'Cherrapunji', 'Known for its heavy rainfall, stunning waterfalls, and limestone caves, Cherrapunji is a paradise for nature lovers.', '../Image/Meghalaya/Cherrapunji.avif');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(62, 24, 'Phawngpui', 'Also known as the Blue Mountain, it is the highest peak in Mizoram and a paradise for trekkers and nature lovers.', '../Image/Mizoram/Phawngpui.jpg'),
(63, 24, 'Luangmual Handicrafts Centre', 'A must-visit place to explore traditional Mizo handicrafts.', '../Image/Mizoram/Luangmual Handicrafts.jpg'),
(64, 24, 'Tamdil Lake', 'A serene and beautiful lake surrounded by lush forests, ideal for picnics and boating.', '../Image/Mizoram/TamdilLake.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(65, 25, 'Dzukou Valley', 'Known as the "Valley of Flowers of the Northeast," it offers breathtaking views, trekking trails, and lush green landscapes.', '../Image/Nagaland/Dzukou Valley.jpg'),
(66, 25, 'Kohima War Cemetery', 'A historic site built in memory of soldiers who lost their lives during World War II, offering a solemn and peaceful environment.', '../Image/Nagaland/KohimaWarCemetery.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(67, 26, 'Konark Sun Temple', 'A UNESCO World Heritage Site, this 13th-century temple is famous for its intricate stone carvings.', '../Image/Odisha/KonarkSunTemple.jpg'),
(68, 26, 'Chilika Lake', 'Asia largest coastal lagoon, home to diverse bird species and a popular spot for boat rides.', '../Image/Odisha/ChilikaLake.webp'),
(69, 26, 'Jagannath Temple', 'A sacred Hindu temple in Puri, famous for the annual Rath Yatra festival.', '../Image/Odisha/Jagannath Temple.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(70, 27, 'Rock Beach', 'A popular beachfront promenade in Puducherry, perfect for sunrise walks, sea breezes, and scenic beauty along the Bay of Bengal.', '../Image/Puducherry/RockBeach.webp'),
(71, 27, 'Auroville', 'An experimental township promoting peace, unity, and sustainable living. The iconic Matrimandir is its centerpiece.', '../Image/Puducherry/Auroville.jpg'),
(72, 27, 'Sri Aurobindo Ashram', 'A spiritual community founded by Sri Aurobindo and The Mother, attracting seekers and tourists alike.', '../Image/Puducherry/SriAurobindoAshram.png');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(73, 28, 'Golden Temple', 'The Golden Temple, located in Amritsar, is one of the holiest shrines for Sikhs. It is known for its beautiful golden dome and serene surroundings. The temple complex also includes the holy pool (Amrit Sarovar), where visitors take a dip for spiritual cleansing. It is a place of immense historical and cultural significance.', '../Image/Punjab/Golden Temple.jpg'),
(74, 28, 'Jallianwala Bagh', 'Jallianwala Bagh is a historical garden in Amritsar, India, where a massacre occurred on April 13, 1919. The event, which involved British soldiers opening fire on unarmed Indian civilians, is a tragic moment in India history. The site is now a memorial and is visited by thousands of people every year to pay their respects.', '../Image/Punjab/Jallianwala Bagh.jpg'),
(75, 28, 'Vaishno Devi Temple', 'The Vaishno Devi Temple, located in Katra in Jammu and Kashmir, is one of the most visited pilgrimage sites for Hindus. It is dedicated to Goddess Vaishno Devi and attracts millions of devotees every year who trek the hills to reach the shrine.', '../Image/Punjab/VaishnoDevi.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(76, 29, 'Amber Fort', 'Located on the outskirts of Jaipur, Amber Fort is a magnificent example of Rajput architecture. The fort is known for its stunning courtyards, intricate carvings, and beautiful mirror palace (Sheesh Mahal). It offers breathtaking views of the surrounding hills and Maota Lake.', '../Image/Rajasthan/Amber Fort.jpg'),
(77, 29, 'Udaipur Lake Palace', 'Located on Lake Pichola, the Lake Palace (now a luxury hotel) is one of the most picturesque palaces in India. It offers stunning views of the lake, the surrounding hills, and the city. Udaipur, known as the "City of Lakes," is famous for its romantic ambiance.', '../Image/Rajasthan/Udaipur Lake Palace.jpg'),
(78, 29, 'Mehrangarh Fort', 'One of the largest and most impressive forts in India, Mehrangarh Fort in Jodhpur stands on a hilltop, offering panoramic views of the city. The fort houses several palaces, museums, and courtyards, showcasing Rajasthan royal history.', '../Image/Rajasthan/Mehrangarh Fort.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(79, 30, 'Tsomgo Lake', 'A glacial lake located at an altitude of 12,400 feet, offering mesmerizing views and surrounded by snow-capped mountains.', '../Image/Sikkim/Tsomgo Lake.png'),
(80, 30, 'Rumtek Monastery', 'One of the most significant monasteries in Sikkim, showcasing rich Buddhist culture and beautiful architecture.', '../Image/Sikkim/Rumtek Monastery.png');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(81, 31, 'Meenakshi Temple', 'A stunning Dravidian-style temple in Madurai, dedicated to Goddess Meenakshi and Lord Sundareswarar.', '../Image/TamilNadu/MeenakshiTemple.png'),
(82, 31, 'Mahabalipuram', 'A UNESCO World Heritage Site famous for its rock-cut temples and shore temples, built during the Pallava dynasty.', '../Image/TamilNadu/Mahabalipuram.jpg'),
(83, 31, 'Ooty', 'A scenic hill station in the Nilgiri Hills, known for its tea gardens, botanical gardens, and pleasant climate.', '../Image/TamilNadu/Ooty.webp');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(84, 32, 'Charminar', 'An iconic 16th-century monument and mosque in Hyderabad, representing the grandeur of the Qutb Shahi dynasty.', '../Image/Telangana/Charminar.jpg'),
(85, 32, 'Ramoji Film City', 'One of the largest film studio complexes in the world, offering guided tours and entertainment experiences.', '../Image/Telangana/Ramoji.png'),
(86, 32, 'Nagarjuna Sagar Dam', 'One of the largest dams in India, offering breathtaking views and boating opportunities.', '../Image/Telangana/NagarjunaSagarDam.jpeg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(87, 33, 'Neer Mahal', 'A stunning water palace located in the middle of Rudrasagar Lake, blending Hindu and Mughal architecture.', '../Image/Tripura/Neer Mahal.webp'),
(88, 33, 'Unakoti', 'An ancient rock-cut site featuring massive stone carvings and sculptures dedicated to Lord Shiva.', '../Image/Tripura/Unakoti.jpg'),
(89, 33, 'Jampui Hills', 'A beautiful hill range offering breathtaking views and known for its orange orchards.', '../Image/Tripura/JampuiHills.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(90, 34, 'Har Ki Pauri', 'Located in Haridwar, Har Ki Pauri is a famous ghat on the banks of the Ganges River. It is a sacred place for Hindus and attracts thousands of pilgrims every year. The evening Ganga Aarti at this ghat is a major attraction for visitors.', '../Image/Uttarakhand/Har Ki Pauri.jpg'),
(91, 34, 'Valley of Flowers', 'The Valley of Flowers National Park is a UNESCO World Heritage site located in the western Himalayas. This enchanting valley is covered with a variety of wildflowers during the monsoon season, making it one of the most beautiful places to visit in Uttarakhand.', '../Image/Uttarakhand/Valley of Flowers.jpg'),
(92, 34, 'Rishikesh', 'Rishikesh, known as the ''Yoga Capital of the World,'' is a spiritual town located on the banks of the Ganges River. It is a major center for yoga and meditation, and it also attracts adventure seekers for activities like white-water rafting and trekking.', '../Image/Uttarakhand/Rishikesh.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(93, 35, 'Taj Mahal', 'One of the Seven Wonders of the World, this white marble mausoleum in Agra is a UNESCO World Heritage Site and a symbol of love.', '../Image/UttarPradesh/Taj Mahal.avif'),
(94, 35, 'Varanasi Ghats', 'The sacred ghats of Varanasi along the Ganges River are a major pilgrimage site, known for their spiritual ambiance and evening Ganga Aarti.', '../Image/UttarPradesh/Varanasi Ghat.png'),
(95, 35, 'Fatehpur Sikri', 'A historic city built by Emperor Akbar, known for its stunning red sandstone architecture and the famous Buland Darwaza.', '../Image/UttarPradesh/FatehpurSikri.jpg');

INSERT INTO tourist_places (id, state_id, name, description, image_url) VALUES
(96, 36, 'Victoria Memorial', 'A grand marble monument in Kolkata, built in memory of Queen Victoria, showcasing British-era architecture.', '../Image/WestBengal/VictoriaMemorial.jpg'),
(97, 36, 'Darjeeling', 'A scenic hill station known for its tea gardens, toy train, and panoramic views of the Himalayas.', '../Image/WestBengal/Darjeeling.jpg'),
(98, 36, 'Sundarbans', 'A UNESCO World Heritage Site and the largest mangrove forest, home to the Royal Bengal Tiger.', '../Image/WestBengal/Sundarbans.jpg');


CREATE TABLE traditional_wears (
    id BIGINT PRIMARY KEY,
    state_id BIGINT,
    men_wear VARCHAR(255),
    women_wear VARCHAR(255),
    image_url VARCHAR(255),
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE CASCADE
);

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(1, 1, 'Casual Shirts & Lungis', 'Floral Dresses & Sarongs', '../Image/AndamanNicobar/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(2, 2, 'Dhoti & Kurta', 'Saree', '../Image/AndhraPradesh/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(3, 3, 'Gale & Jacket', 'Gale with Ornaments', '../Image/ArunachalPradesh/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(4, 4, 'Dhoti & Gamosa', 'Mekhela Chador', '../Image/Assam/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(5, 5, 'Dhoti & Kurta', 'Tussar Silk Saree', '../Image/Bihar/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(6, 6, 'Kurta Pajama & Nehru Jacket', 'Salwar Kameez & Phulkari Dupatta', '../Image/Chandigarh/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(7, 7, 'Dhoti & Angarkha', 'Lugda & Kachhora', '../Image/Chhattisgarh/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(8, 8, 'Dhoti & Kurta', 'Ghagra Choli & Saree', '../Image/DadraNagarHaveliDamanDiu/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(9, 9, 'Kurta Pajama & Sherwani', 'Saree & Salwar Kameez', '../Image/Delhi/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(10, 10, 'Kashti & Kunbi Shawl', 'Pano Bhaju & Kunbi Saree', '../Image/Goa/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(11, 11, 'Kediyu & Dhoti', 'Chaniya Choli & Bandhani Saree', '../Image/Gujarat/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(12, 12, 'Dhoti & Kurta', 'Salwar Kameez & Dupatta', '../Image/Haryana/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(13, 13, 'Kullu Shawl & Kurta', 'Chamba Chappal & Pattu', '../Image/HimachalPradesh/Wear.webp');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(14, 14, 'Shalwar Kameez & Pheran', 'Pheran & Head Scarf', '../Image/JammuKhasmir/Wear.avif');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(15, 15, 'Kurta & Dhoti', 'Tussar Silk Saree', '../Image/Jharkhand/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(16, 16, 'Panche & Kurta', 'Mysore Silk Saree', '../Image/Karnataka/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(17, 17, 'Mundu & Shirt', 'Kasavu Saree', '../Image/Kerala/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(18, 18, 'Chuba', 'Kata', '../Image/Ladakh/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(19, 19, 'Mundu & Shirt', 'Kacha & Blouse', '../Image/Lakshadweep/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(20, 20, 'Dhoti & Safa', 'Chanderi Saree & Lehenga Choli', '../Image/MadhyaPradesh/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(21, 21, 'Dhoti & Kurta', 'Nauvari Saree & Paithani Saree', '../Image/Maharashtra/Wear.avif');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(22, 22, 'Dhoti & Kurta', 'Phanek & Innaphi', '../Image/Manipur/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(23, 23, 'Jymphong', 'Jainsem', '../Image/Meghalaya/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(24, 24, 'Puandum & Puanchei', 'Puanchei & Kawrechi', '../Image/Mizoram/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(25, 25, 'Warrior Shawls', 'Mechala and Shawl', '../Image/Nagaland/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(26, 26, 'Dhoti & Kurta', 'Sambalpuri Saree', '../Image/Odisha/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(27, 27, 'Dhoti & Shirt', 'Saree or Salwar Kameez (with some French-influenced styles)', '../Image/Puducherry/Wear.jpeg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(28, 28, 'Kurta & Pyjama', 'Salwar Kameez & Dupatta', '../Image/Punjab/Wear.webp');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(29, 29, 'Dhoti & Kurta', 'Lehenga Choli', '../Image/Rajasthan/Wear.webp');
INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(30, 30, 'Bakhu & Thokro-Dum', 'Bakhu with Honju', '../Image/Sikkim/Wear.png');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(31, 31, 'Veshti & Angavastram', 'Kanjeevaram Saree', '../Image/TamilNadu/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(32, 32, 'Pancha & Sherwani', 'Pochampally Saree & Langa Voni', '../Image/Telangana/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(33, 33, 'Rikutu & Kamchwlwi', 'Risa, Rignai & Rikutu', '../Image/Tripura/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(34, 34, 'Dhoti & Kurta', 'Ghagra & Choli', '../Image/Uttarakhand/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(35, 35, 'Dhoti Kurta & Sherwani', 'Lehenga & Saree', '../Image/UttarPradesh/Wear.jpg');

INSERT INTO traditional_wears (id, state_id, men_wear, women_wear, image_url) VALUES
(36, 36, 'Panjabi & Dhoti', 'Tant Saree & Baluchari Saree', '../Image/WestBengal/Wear.webp');



CREATE TABLE festivals (
    id BIGINT PRIMARY KEY,
    state_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    FOREIGN KEY (state_id) REFERENCES states(id) ON DELETE CASCADE
);

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(1, 1, 'Island Tourism Festival', 'A 10-day festival celebrating the culture, music, and traditions of the islands, featuring dance performances and handicrafts exhibitions.', '../Image/AndamanNicobar/IslandTourism.jpg'),
(2, 1, 'Deepawali', 'The festival of lights is widely celebrated across the islands with traditional decorations and community gatherings.', '../Image/AndamanNicobar/Deepawali.jpg'),
(3, 1, 'Durga Puja', 'A major festival in the Andaman Islands, celebrated with grandeur, featuring beautifully crafted idols and cultural events.', '../Image/AndamanNicobar/DurgaPuja.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(4, 2, 'Ugadi', 'Ugadi marks the beginning of the New Year in Andhra Pradesh. It is celebrated with great enthusiasm, with people decorating their homes, wearing new clothes, and offering prayers. Special dishes, such as Ugadi pachadi, are prepared, symbolizing different emotions of life: sweet, sour, bitter, and salty.', '../Image/AndhraPradesh/Ugadi.jpg'),
(5, 2, 'Pongal', 'Pongal is a harvest festival celebrated to thank the Sun God for a good harvest. It is celebrated with much fervor in Andhra Pradesh, especially in rural areas. People cook "Pongal," a dish made from newly harvested rice, and offer it as a token of gratitude for the harvest. The festival is marked by colorful decorations, traditional dance, and music.', '../Image/AndhraPradesh/Pongal.jpg'),
(6, 2, 'Ratha Saptami', 'Ratha Saptami is a significant Hindu festival dedicated to the Sun God. It is believed to be the day when the Sun God begins his northward journey. Devotees celebrate the festival by performing special rituals, including taking holy dips in rivers, offering prayers, and observing fasting. The festival is also marked by processions and chariot rides.', '../Image/AndhraPradesh/Ratha saptami.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(7, 3, 'Losar Festival', 'Celebrated by the Monpa tribe, Losar marks the Tibetan New Year with prayers, dances, and feasts.', '../Image/ArunachalPradesh/Losar Festival.webp'),
(8, 3, 'Solung Festival', 'A major festival of the Adi tribe, celebrated with rituals, folk dances, and communal feasting.', '../Image/ArunachalPradesh/Solung Festival.png');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(9, 4, 'Bihu Festival', 'The most important festival of Assam, celebrated with dance, music, and feasting, marking the Assamese New Year.', '../Image/Assam/Bihu Festival.png'),
(10, 4, 'Ambubachi Mela', 'A unique spiritual festival held at the Kamakhya Temple, celebrating the fertility of the goddess Kamakhya.', '../Image/Assam/Ambubachi Mela.png');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(11, 5, 'Chhath Puja', 'The most important festival in Bihar, dedicated to the Sun God, where devotees offer prayers on riverbanks.', '../Image/Bihar/Chhath Puja.png'),
(12, 5, 'Sama Chakeva', 'A folk festival celebrated by women, marking the bond between brothers and sisters.', '../Image/Bihar/Sama Chakeva.png'),
(13, 5, 'Sonepur Mela', 'One of Asia''s largest cattle fairs, held annually in Sonepur, combining trade, spirituality, and entertainment.', '../Image/Bihar/SonepurMela.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(14, 6, 'Baisakhi', 'A major festival celebrated with enthusiasm, marking the harvest season with dance, music, and fairs.', '../Image/Chandigarh/Baisakhi.jpg'),
(15, 6, 'Lohri', 'The festival of bonfires, celebrated with folk songs, dance, and sweets made of sesame and jaggery.', '../Image/Chandigarh/Lohri.jpg'),
(16, 6, 'Teej', 'A festival celebrated by women with traditional songs, swings, and colorful attire, marking the monsoon season.', '../Image/Chandigarh/Teej.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(17, 7, 'Bastar Dussehra', 'A unique 75-day festival celebrated by the tribal communities with traditional rituals and grand processions.', '../Image/Chhattisgarh/BastarDussehra.jpg'),
(18, 7, 'Madai Festival', 'A tribal festival celebrated with music, dance, and rituals in honor of local deities.', '../Image/Chhattisgarh/MadaiFestival.jpg'),
(19, 7, 'Goncha Festival', 'A unique festival where devotees use handmade wooden guns as part of the celebration.', '../Image/Chhattisgarh/Goncha.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(20, 8, 'Nariyal Purnima', 'A unique festival celebrated by fishermen to mark the end of monsoon and seek blessings for a prosperous fishing season.', '../Image/DadraNagarHaveliDamanDiu/NariyalPurnima.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(21, 9, 'Diwali', 'The festival of lights, celebrated with great enthusiasm through fireworks, sweets, and lighting diyas.', '../Image/Delhi/Diwali.jpg'),
(22, 9, 'Republic Day', 'A grand celebration held at Rajpath with a parade showcasing India rich cultural heritage and military prowess.', '../Image/Delhi/RepublicDay.jpg'),
(23, 9, 'Holi', 'The festival of colors, celebrated with joy, music, and vibrant festivities throughout the city.', '../Image/Delhi/Holi.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(24, 10, 'Goa Carnival', 'A grand celebration filled with colorful parades, music, and dancing, held before Lent.', '../Image/Goa/GoaCarnival.avif'),
(25, 10, 'Feast of St. Francis Xavier', 'An important religious festival honoring Goas patron saint, celebrated with mass gatherings and processions.', '../Image/Goa/FrancisXavier.jpg'),
(26, 10, 'Sao Joao Festival', 'A unique monsoon festival where locals jump into wells and streams to celebrate St. John the Baptist.', '../Image/Goa/SaoJoao.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(27, 11, 'Navratri', 'A grand festival celebrated with nine nights of Garba and Dandiya Raas, making it the most famous event in Gujarat.', '../Image/Gujarat/Navratri.jpg'),
(28, 11, 'Uttarayan', 'The International Kite Festival, marking the transition of the sun into Capricorn, where the sky is filled with colorful kites.', '../Image/Gujarat/Uttarayan.jpg'),
(29, 11, 'Rann Utsav', 'A cultural festival held in the Rann of Kutch, featuring folk music, dance, and traditional handicrafts.', '../Image/Gujarat/RannUtsav.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(30, 12, 'Makar Sankranti', 'Makar Sankranti is one of the most celebrated festivals in Haryana, marking the arrival of the harvest season. People celebrate by flying kites, dancing, and enjoying festive foods like tilgul (sesame and jaggery sweets). The festival is celebrated with much enthusiasm and joy.', '../Image/Haryana/Makar Sankranti.png'),
(31, 12, 'Teej Festival', 'Teej is a traditional festival celebrated by women in Haryana, marking the arrival of monsoon. Women dress up in vibrant clothes, adorn themselves with jewelry, and participate in singing, dancing, and fasting for the well-being of their husbands.', '../Image/Haryana/Teej Festival.jpg'),
(32, 12, 'Holi', 'Holi, the festival of colors, is celebrated with great enthusiasm in Haryana. People come together to play with colors, share sweets, and celebrate the arrival of spring. The festival brings people of all ages together to celebrate joy, love, and unity.', '../Image/Haryana/Holi.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(33, 13, 'Kullu Dussehra', 'A week-long festival celebrated in the Kullu Valley, marking the victory of good over evil. The festival is known for its cultural performances, processions of deities, and traditional rituals. It is one of the most important festivals in Himachal Pradesh.', '../Image/HimachalPradesh/KulluDussehra.jpg'),
(34, 13, 'Phulaich', 'A unique festival celebrated by the Kullu people, marking the arrival of spring. During Phulaich, people offer prayers, sing traditional songs, and engage in festive dances. The festival is associated with the blossoming of wildflowers in the region.', '../Image/HimachalPradesh/Phulaich.jpg'),
(35, 13, 'Malani Mela', 'Celebrated annually in the Malana village, this festival showcases the regions local culture, traditional music, and vibrant dances. Malana is known for its unique customs and practices, and the Malani Mela is an important part of their cultural heritage.', '../Image/HimachalPradesh/MalaniMela.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(36, 14, 'Eid al-Fitr', 'Eid is one of the most celebrated festivals in Jammu & Kashmir, marking the end of Ramadan. It is a time for family gatherings, prayers, and feasting. The regions vibrant traditions make it a joyous occasion.', '../Image/JammuKhasmir/Eid.webp'),
(37, 14, 'Navratri', 'A major Hindu festival celebrated with devotion and zeal. In Jammu & Kashmir, the festival is marked by prayers, fasting, dance, and cultural events. The Katra region, where Vaishno Devi temple is located, is especially vibrant during this period.', '../Image/JammuKhasmir/Navratri.jpg'),
(38, 14, 'Lohri', 'A festival celebrated predominantly in Jammu, marking the end of winter and the beginning of the harvest season. The festivities include lighting bonfires, singing folk songs, and dancing.', '../Image/JammuKhasmir/Lohri.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(39, 15, 'Sarhul', 'A tribal festival celebrating the worship of trees and nature, marked by dances and rituals.', '../Image/Jharkhand/Sarhul.jpg'),
(40, 15, 'Karma Festival', 'A significant festival for tribal communities, symbolizing prosperity and well-being.', '../Image/Jharkhand/KarmaFestival.jpg'),
(41, 15, 'Chhath Puja', 'A major festival where devotees worship the Sun God, offering prayers on riverbanks.', '../Image/Jharkhand/ChhathPuja.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(42, 16, 'Mysore Dussehra', 'A grand festival celebrated in Mysore with processions, cultural performances, and royal events.', '../Image/Karnataka/MysoreDussehra.webp'),
(43, 16, 'Ugadi', 'The Kannada New Year, marked by special rituals, feasts, and the preparation of Ugadi Pachadi.', '../Image/Karnataka/Ugadi.jpg'),
(44, 16, 'Kambala', 'A traditional buffalo race held in coastal Karnataka, showcasing the region''s rural heritage.', '../Image/Karnataka/Kambala.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(45, 17, 'Onam', 'Kerala''s biggest festival, celebrated with grand feasts, floral decorations, boat races, and cultural performances.', '../Image/Kerala/Onam.jpg'),
(46, 17, 'Vishu', 'The Malayali New Year, marked by special rituals, feasting, and the Vishukkani sighting for prosperity.', '../Image/Kerala/Vishu.jpg'),
(47, 17, 'Thrissur Pooram', 'A grand temple festival known for its vibrant elephant procession, fireworks, and traditional music.', '../Image/Kerala/ThrissurPooram.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(48, 18, 'Losar', 'Losar is the Ladakhi New Year festival, celebrated with traditional dances, rituals, and feasts. It marks the beginning of a new year according to the lunar calendar and is a time for family reunions and community gatherings.', '../Image/Ladakh/Losar.webp'),
(49, 18, 'Indus River Festival', 'Celebrated on the banks of the Indus River, this festival highlights Ladakhi culture, music, and dance. It is one of the most anticipated events in Ladakh, bringing together locals and tourists to celebrate the region''s heritage.', '../Image/Ladakh/Indus River Festival.webp'),
(50, 18, 'Phyang Festival', 'Held annually at Phyang Monastery, this festival is known for its vibrant traditional dances, music, and performances by local monks. It is a celebration of Ladakhi Buddhism and the region''s spiritual practices.', '../Image/Ladakh/Phyang.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(51, 19, 'Eid', 'A significant festival in Lakshadweep, celebrated with prayers, feasts, and community gatherings.', '../Image/Lakshadweep/Eid.png');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(52, 20, 'Lokrang Festival', 'A cultural festival in Bhopal showcasing folk art, music, and dance from different regions of India.', '../Image/MadhyaPradesh/LokrangFestival.webp'),
(53, 20, 'Tansen Samaroh', 'A prestigious music festival in Gwalior dedicated to the legendary musician Tansen, featuring classical music performances.', '../Image/MadhyaPradesh/TansenSamaroh.webp'),
(54, 20, 'Bhagoria Festival', 'A vibrant tribal festival celebrated by the Bhil and Bhilala communities, known for its unique tradition of matchmaking.', '../Image/MadhyaPradesh/BhagoriaFestival.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(55, 21, 'Ganesh Chaturthi', 'The most famous festival in Maharashtra, celebrated with grandeur, processions, and immersion of Lord Ganesha idols.', '../Image/Maharashtra/GaneshChaturthi.webp'),
(56, 21, 'Gudi Padwa', 'The Maharashtrian New Year, marked by the raising of the Gudi flag and traditional celebrations.', '../Image/Maharashtra/GudiPadwa.webp'),
(57, 21, 'Diwali', 'The festival of lights, celebrated with rangoli, sweets, and firecrackers.', '../Image/Maharashtra/Diwali.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(58, 22, 'Yaoshang', 'The Manipuri version of Holi, celebrated with cultural performances and sports events.', '../Image/Manipur/Yaoshang.jpg'),
(59, 22, 'Ningol Chakouba', 'A festival that strengthens family bonds, where married women return to their parental home for a grand feast.', '../Image/Manipur/Ningol Chakouba.avif');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(60, 23, 'Shad Suk Mynsiem', 'A significant Khasi festival, celebrated with traditional dance and music, symbolizing joy and thanksgiving.', '../Image/Meghalaya/Shad Suk Mynsiem.jpg'),
(61, 23, 'Wangala Festival', 'A harvest festival of the Garo tribe, marked by drumming, dancing, and rituals dedicated to the Sun God.', '../Image/Meghalaya/Wangala Festival.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(62, 24, 'Chapchar Kut', 'The most popular Mizo festival, celebrated with traditional dances and music.', '../Image/Mizoram/Chapchar Kut.jpg'),
(63, 24, 'Mim Kut', 'A harvest festival celebrated in honor of deceased ancestors with traditional feasts and dances.', '../Image/Mizoram/MimKut.jpg'),
(64, 24, 'Pawl Kut', 'A post-harvest festival marking the end of the agricultural season with feasting and festivities.', '../Image/Mizoram/PawlKut.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(65, 25, 'Hornbill Festival', 'A grand celebration of Naga culture, featuring traditional dance, music, crafts, and local cuisines.', '../Image/Nagaland/HornbillFestival.jpg'),
(66, 25, 'Moatsu Festival', 'A significant festival of the Ao tribe, celebrated with great enthusiasm through folk dances, songs, and feasting.', '../Image/Nagaland/Moatsu Festival.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(67, 26, 'Rath Yatra', 'The grand chariot festival of Lord Jagannath, celebrated in Puri with massive processions.', '../Image/Odisha/RathYatra.avif'),
(68, 26, 'Nuakhai', 'A harvest festival celebrated in western Odisha, marking the new rice crop season.', '../Image/Odisha/Nuakhai.webp'),
(69, 26, 'Makar Sankranti', 'A major festival where people take holy dips and fly kites to celebrate the change of seasons.', '../Image/Odisha/MakarSankranti.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(70, 27, 'Bastille Day', 'Celebrated on July 14th, it includes parades and cultural events reflecting Puducherrys French heritage. Ex-servicemen march in uniform through the streets carrying the French and Indian flags.', '../Image/Puducherry/BastilleDay.jpg'),
(71, 27, 'Diwali', 'The Festival of Lights is celebrated with grandeur in Puducherry, with firecrackers, sweets, and festive decorations adorning homes and streets.', '../Image/Puducherry/Diwali.jpg'),
(72, 27, 'Masi Magam', 'A significant Tamil festival observed with processions of deities from temples to the sea for a ceremonial bath, attracting large crowds and spiritual gatherings.', '../Image/Puducherry/MasiMagam.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(73, 28, 'Baisakhi', 'Baisakhi is the harvest festival of Punjab, celebrated with much enthusiasm. It marks the beginning of the harvest season and is also significant in Sikhism as the formation of the Khalsa was on this day. People celebrate Baisakhi by dancing the Bhangra and Gidda, singing folk songs, and enjoying traditional food.', '../Image/Punjab/Baisakhi.jpeg'),
(74, 28, 'Diwali', 'Diwali, also known as the Festival of Lights, is widely celebrated in Punjab. The festival marks the victory of light over darkness and good over evil. People celebrate by decorating their homes with diyas (oil lamps), bursting fireworks, and enjoying sweets.', '../Image/Punjab/Diwali.webp'),
(75, 28, 'Lohri', 'Lohri is a popular Punjabi festival marking the end of winter and the beginning of the harvest season. It is celebrated by lighting bonfires, singing folk songs, and dancing to the rhythms of the dhol. Lohri is especially popular in rural areas.', '../Image/Punjab/Lohri.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(76, 29, 'Pushkar Fair', 'The Pushkar Fair is one of the largest and most famous animal fairs in the world. Held annually in the town of Pushkar, the fair features camel trading, folk music and dance, cultural performances, and a lively atmosphere. It is a major cultural event in Rajasthan.', '../Image/Rajasthan/Pushkar Fair.jpg'),
(77, 29, 'Diwali', 'Diwali, the festival of lights, is celebrated with much fanfare in Rajasthan. Homes are decorated with oil lamps and colorful rangolis, and people celebrate by exchanging sweets, bursting crackers, and offering prayers to Goddess Lakshmi for wealth and prosperity.', '../Image/Rajasthan/Diwali.jpg'),
(78, 29, 'Teeyan', 'Teeyan is a festival celebrated by women in Rajasthan, especially in the monsoon season. Women dress in colorful attire, sing traditional songs, and celebrate with dancing and festive foods. It is a celebration of womanhood and the arrival of the monsoon rains.', '../Image/Rajasthan/Teeyan.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(79, 30, 'Losoong Festival', 'Celebrated as the Sikkimese New Year, Losoong marks the end of the harvest season and is observed with traditional dances and rituals.', '../Image/Sikkim/Losoong Festival.png'),
(80, 30, 'Maghe Sankranti', 'A major Hindu festival celebrated in Sikkim with holy dips, prayers, and feasting, marking the transition of the sun.', '../Image/Sikkim/Maghe Sankranti.png');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(81, 31, 'Pongal', 'A major harvest festival in Tamil Nadu, celebrated with traditional cooking of Pongal, cattle worship, and cultural events.', '../Image/TamilNadu/Pongal.webp'),
(82, 31, 'Karthigai Deepam', 'A festival of lights where lamps are lit in homes and temples, with grand celebrations at Arunachaleswarar Temple.', '../Image/TamilNadu/KarthigaiDeepam.jpg'),
(83, 31, 'Jallikattu', 'A traditional bull-taming sport held during Pongal in Tamil Nadu, showcasing bravery and cultural heritage.', '../Image/TamilNadu/Jallikattu.jpeg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(84, 32, 'Bathukamma', 'A unique floral festival celebrated by women in Telangana, involving colorful flower arrangements and traditional songs.', '../Image/Telangana/Bathukamma.jpg'),
(85, 32, 'Bonalu', 'A Hindu festival dedicated to Goddess Mahakali, marked by grand processions, rituals, and offerings.', '../Image/Telangana/Bonalu.jpg'),
(86, 32, 'Sammakka Saralamma Jatara', 'One of the largest tribal festivals in India, attracting millions of devotees.', '../Image/Telangana/SammakkaSaralammaJatara.webp');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(87, 33, 'Garia Puja', 'A significant tribal festival celebrated to worship the deity Baba Garia for prosperity and well-being.', '../Image/Tripura/GariaPuja.png'),
(88, 33, 'Kharchi Puja', 'A week-long festival dedicated to the 14 deities, performed with grand rituals and celebrations.', '../Image/Tripura/KharchiPuja.webp'),
(89, 33, 'Poush Sankranti', 'A harvest festival marking the transition of the sun into Capricorn, celebrated with feasting and cultural performances.', '../Image/Tripura/PoushSankranti.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(90, 34, 'Kumbh Mela', 'The Kumbh Mela is one of the largest religious gatherings in the world, held in Haridwar, Uttarakhand. Millions of devotees gather to take a holy dip in the Ganges River. The Kumbh Mela occurs once every 12 years and is celebrated with much fanfare, with devotees taking part in rituals and prayers.', '../Image/Uttarakhand/KumbhMela.jpg'),
(91, 34, 'Makar Sankranti', 'Makar Sankranti is a festival that marks the transition of the sun into the zodiac sign of Capricorn. In Uttarakhand, this festival is celebrated with kite flying, bonfires, and various cultural performances. It is one of the most popular festivals in the state.', '../Image/Uttarakhand/Makar Sankranti.jpg'),
(92, 34, 'Tulsi Vivah', 'Tulsi Vivah is an important Hindu festival celebrated in Uttarakhand. It marks the ceremonial marriage of the Tulsi plant to Lord Vishnu. The festival is celebrated with great devotion, especially in rural areas, where people offer prayers and perform rituals in temples and homes.', '../Image/Uttarakhand/Tulsi Vivah.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(93, 35, 'Kumbh Mela', 'The largest religious gathering in the world, held every 12 years in Prayagraj, attracting millions of devotees for holy dips in the Ganges.', '../Image/UttarPradesh/Kumbh Mela.png'),
(94, 35, 'Holi', 'The festival of colors is grandly celebrated in Mathura and Vrindavan, associated with the legends of Lord Krishna.', '../Image/UttarPradesh/Holi.jpg'),
(95, 35, 'Diwali', 'The festival of lights, celebrated across Uttar Pradesh, is particularly famous in Ayodhya, where grand celebrations mark Lord Rama''s return.', '../Image/UttarPradesh/Diwali.jpg');

INSERT INTO festivals (id, state_id, name, description, image_url) VALUES
(96, 36, 'Durga Puja', 'The biggest festival of West Bengal, celebrated with grandeur, artistic idols, and cultural performances.', '../Image/WestBengal/DurgaPuja.webp'),
(97, 36, 'Poush Mela', 'A traditional fair held in Shantiniketan, celebrating Bengali folk culture, music, and crafts.', '../Image/WestBengal/PoushMela.jpg'),
(98, 36, 'Rath Yatra', 'A famous chariot festival celebrated in ISKCON temples across West Bengal, particularly in Kolkata.', '../Image/WestBengal/RathYatra.jpg');


CREATE TABLE national_symbols (
    id VARCHAR(50) PRIMARY KEY,
    emoji VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    since VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    bg VARCHAR(100) NOT NULL,
    accent VARCHAR(20) NOT NULL,
    fact TEXT NOT NULL,
    tags VARCHAR(100) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    specialBg BOOLEAN DEFAULT FALSE
);

INSERT INTO national_symbols (id, emoji, category, title, name, since, color, bg, accent, fact, tags, image_url, specialBg) VALUES
('bird', '🦚', 'Wildlife', 'National Bird', 'Peacock', '1963', '#00b4d8', 'linear-gradient(135deg,#e0f7ff,#b3ecff)', '#005f80', 'The peacock''s dazzling tail feathers, called a "train," can be up to 6 feet long and feature iridescent "eye" patterns.', 'Protected,Migratory', '../Image/Symbols/Peacock.jpeg', FALSE),
('animal', '🐯', 'Wildlife', 'National Animal', 'Bengal Tiger', '1973', '#FF9933', 'linear-gradient(135deg,#fff3e0,#ffe0b2)', '#7a4000', 'India is home to over 70% of the world''s wild tiger population. Project Tiger was launched the same year it became the national animal.', 'Endangered,Project Tiger', '../Image/Symbols/Tiger.jpg', FALSE),
('flower', '🪷', 'Flora', 'National Flower', 'Lotus', 'Ancient', '#ff006e', 'linear-gradient(135deg,#ffe0ef,#ffb3d1)', '#7a0033', 'The lotus blooms in muddy water yet remains unstained — a symbol of purity, enlightenment, and self-regeneration in Indian culture.', 'Sacred,Aquatic', '../Image/Symbols/Lotus.jpeg', FALSE),
('tree', '🌳', 'Flora', 'National Tree', 'Indian Banyan', 'Traditional', '#138808', 'linear-gradient(135deg,#e8fded,#c6f6d5)', '#1a5c2a', 'A single Banyan tree can spread over several acres through its aerial prop roots. The Great Banyan in Kolkata is over 250 years old.', 'Sacred,Evergreen', '../Image/Symbols/Banyan.jpeg', FALSE),
('fruit', '🥭', 'Flora', 'National Fruit', 'Mango', 'Traditional', '#ffbe0b', 'linear-gradient(135deg,#fff8e0,#ffe680)', '#5a4000', 'India is the world''s largest mango producer with over 1,000 varieties. Mangoes have been cultivated here for more than 5,000 years.', 'Tropical,5000+ Years', '../Image/Symbols/Mango.jpg', FALSE),
('river', '🏞️', 'Geography', 'National River', 'Ganga (Ganges)', '2008', '#00b4d8', 'linear-gradient(135deg,#e0f7ff,#c8f0ff)', '#003a52', 'The Ganga is 2,525 km long and considered sacred by over 400 million people. It supports the world''s most densely populated river basin.', 'Sacred,2525 km', '/..Image/Symbols/Ganga.jpeg', FALSE),
('sport', '🏑', 'Culture', 'National Sport', 'Field Hockey', 'Traditional', '#3a86ff', 'linear-gradient(135deg,#e0eaff,#b3ccff)', '#003080', 'India dominated Olympic hockey from 1928–1956, winning 6 consecutive gold medals. Legends like Dhyan Chand made it the golden era of Indian hockey.', 'Olympic Gold ×8,Legacy', '../Image/Symbols/Hockey.jpeg', FALSE),
('emblem', '🏛️', 'State', 'National Emblem', 'Lion Capital of Ashoka', '1950', '#8338ec', 'linear-gradient(135deg,#f0e8ff,#d9b3ff)', '#4a0080', 'Adopted on 26 Jan 1950, it features four Asiatic lions on an abacus with the motto "Satyameva Jayate" (Truth alone triumphs) from the Mundaka Upanishad.', 'Republic Day,Ashoka Pillar', '../Image/Symbols/Emblem.jpg', FALSE),
('currency', '₹', 'State', 'National Currency', 'Indian Rupee', '2010', '#06d6a0', 'linear-gradient(135deg,#e0fff7,#b3ffea)', '#005a40', 'The ₹ symbol was designed by D. Udaya Kumar in 2010. It blends the Devanagari "र" with the Latin "R", reflecting India''s bilingual identity.', 'Symbol 2010,Devanagari', '../Image/Symbols/Rupee.jpg', FALSE),
('anthem', '🎵', 'Culture', 'National Anthem', 'Jana Gana Mana', '1950', '#fb5607', 'linear-gradient(135deg,#ffe8e0,#ffbfaa)', '#7a2000', 'Written by Rabindranath Tagore in 1911, it takes exactly 52 seconds to sing. It was adopted as the national anthem on 24 January 1950.', 'Tagore,52 Seconds', '../Image/Symbols/Anthem.jpg', FALSE),
('song', '🎶', 'Culture', 'National Song', 'Vande Mataram', '1950', '#d62828', 'linear-gradient(135deg,#ffe0e0,#ffb3b3)', '#7a0000', 'Composed by Bankim Chandra Chatterjee in 1882, it became the inspiration for Indian independence movement. The first two stanzas hold equal status with the anthem.', '1882,Independence', '../Image/Symbols/Song.webp', FALSE),
('aquatic', '🐬', 'Wildlife', 'National Aquatic Animal', 'Ganges River Dolphin', '2009', '#4361ee', 'linear-gradient(135deg,#e8ecff,#c5ccff)', '#1a237e', 'Nearly blind, this dolphin navigates entirely by echolocation. It is a symbol of the purity and health of the Ganga river ecosystem.', 'Endangered,Echolocation', '../Image/Symbols/Dolphin.jpeg', FALSE),
('reptile', '🐍', 'Wildlife', 'National Reptile', 'King Cobra', 'Traditional', '#4a4e69', 'linear-gradient(135deg,#ecedf5,#d0d2e8)', '#22223b', 'The King Cobra is the world''s longest venomous snake, reaching up to 5.5 metres. Uniquely, it builds nests to guard its eggs.', '5.5m Longest,Nests Eggs', '../Image/Symbols/Cobra.jpeg', FALSE),
('heritage', '🐘', 'Wildlife', 'National Heritage Animal', 'Indian Elephant', '2010', '#7f5af0', 'linear-gradient(135deg,#ede7ff,#d0baff)', '#3b0086', 'India has the largest Asian elephant population in the world. Elephants have played a central role in Indian culture, religion, and warfare for millennia.', 'Largest Pop.,Sacred', '../Image/Symbols/Elephant.jpeg', FALSE),
('calendar', '📅', 'State', 'National Calendar', 'Saka Calendar', '1957', '#e07a5f', 'linear-gradient(135deg,#fde8e0,#f8c8b8)', '#7a2800', 'Adopted on 22 March 1957, the Saka era began in 78 CE. The calendar has 12 months, with Chaitra as the first month, used in official government communications.', '78 CE Origin,Official', '../Image/Symbols/Calendar.webp', FALSE),
('flag', 'Flag.png', 'State', 'National Flag', 'Tiranga', '1947', '#FF9933', 'linear-gradient(135deg,#fff9f0,#fff3e0)', '#5a3000', 'The tricolour features saffron (courage), white (peace & truth), and green (faith & chivalry). The navy blue Ashoka Chakra at centre has 24 spokes.', '24 Spokes,Tiranga', '../Image/Symbols/flag_real.jpg', TRUE);




