spring.application.name=backend

server.port=8081


# Database connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/KnowBharat
spring.datasource.username=######
spring.datasource.password=######

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Optional: PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=#######
spring.mail.password=#######
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# REDIS & CACHING CONFIGURATION
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Leave password blank if you installed Memurai or standard Docker Redis
spring.data.redis.password=

# Tell Spring to use Redis for the @Cacheable annotations
spring.cache.type=redis
# Optional: Set cached data to expire after 24 hours (in milliseconds) so it stays fresh
spring.cache.redis.time-to-live=86400000